### ISSUE TITLE
math formula display

### ISSUE THREAD

**Issue by xzenggit** [qckanemoto/jekyll-qck-theme#17]
Hello,

I'm currently using this template for my blog. Very nice work! However, some math formulas can not show correctly. See http://xzenggit.github.io/en/2016/01/03/common-algorithms/. I'm not very familiar with the _config.yml file. Could you take a look of my _config.yml at https://github.com/xzenggit/en/blob/gh-pages/_config.yml and see if I need add some extensions ? Thank you very much.

**Comment by ttskch** [comment]
@xzenggit Thanks for reporting. I figured out that [_syntax.scss](https://github.com/xzenggit/en/blob/gh-pages/_sass/base/_syntax.scss) conflicts with MathJax output. [#20](https://github.com/qckanemoto/jekyll-qck-theme/pull/20/files) and [#22](https://github.com/qckanemoto/jekyll-qck-theme/pull/22/files) will resolve your problem. Please try them on your repository.

**Comment by ttskch** [comment]
closing this issue ✋
