### ISSUE TITLE
Improve headers hierarchy

### ISSUE THREAD

**Issue by ggarnier** [qckanemoto/jekyll-qck-theme#28]
I just noticed the `h1` tag is used not only in the page header (for the site title), but also in the posts title and sidebar titles (like "Related posts"). Shouldn't `h1` be used only in the site title, and the other ones be replaced with `h2`?

**Comment by ttskch** [comment]
@ggarnier Thanks for your advice! I think you're right. In principle, we shouldn't use multiple `h1` in one page. But at the same time I also think that both of SITE TITLE and POST TITLE are most important information appropriate for `h1`. I don't have the best idea for this problem... But at least, sidebar titles (like `Related posts`) have to be replaced with `h2` I think 👍 Could you please some PR?

**Comment by ggarnier** [comment]
@ttskch sure, I'll work on that
