### ISSUE TITLE
liquid syntax warnings in default.html

### ISSUE THREAD

**Issue by gernotstarke** [qckanemoto/jekyll-qck-theme#44]
Liquid Warning: Liquid syntax error (line 71): Expected dotdot but found pipe in "{{(site.pages | sort: 'order') }}" in /_layouts/default.html

with more recend jekyll versions (like 3.x.x) I get this warning

**Comment by ttskch** [comment]
@gernotstarke Sorry for my late response 🙇This warning is already solved via #39 I think. Please update your codebase. Thanks.
