### ISSUE TITLE
Description directive typos in default layout cause malformed HTML

### ISSUE THREAD

**Issue by neontapir** [qckanemoto/jekyll-qck-theme#9]
There are a couple of cases in `_layout/default.html` where `{{ site.description }}` is simply `{{ description }}`, which leads to site generation errors.

**Comment by qckanemoto** [comment]
So sorry for my late reply.
I think there is no problem because `description` is correctly defined [here](https://github.com/qckanemoto/jekyll-qck-theme/blob/master/_layouts/default.html#L8-L12).

**Comment by ttskch** [comment]
closed via #10
